### PR TITLE
Rebranding of etherpad.

### PR DESCRIPTION
**Pull request by Gaxxey**
In addition to the new logo, 

* added a familiar but more welcoming color-scheme throughout (headers, links, footer)

* Removed gray backgrounds in-favor of white with drop-shadows on images for contrast. 

* New favicon to match logo.

### CODE REVIEW

**Comment by Gaxxey** [comment]
## Preview

etherpad-before

## New

etherpad-now

**Comment by JohnMcLear** [comment]
Cc @seballot

**Comment by seballot** [comment]
Great job ! looks very nice :)

Re the logo, I like it ! but I find that the icon is a bit big in comparaison of the "etherpad" text, don't you think? Either make "Etherpad" with capital E, and/or reduce a bit the size of the icon?

Ps : did you also solve in the meantime this funny link?
image

**Comment by JohnMcLear** [comment]
Awesome job thanks! :D

**Comment by JohnMcLear** [comment]
If you need any help making edits to core editor or whatever just lemme know, I maintain most of the plugins so happy to help.

**Comment by Gaxxey** [comment]
Usually you want the text about half the size of the logo to give it a hierarchical design, easier for the eye to follow than having things on the same plane.  I've lowered the logo size a bit, I can adjust it more if you'd like. 

Heres the fixed overview bar
overview-bar

**Comment by JohnMcLear** [comment]
we cover favicon here?

**Comment by JohnMcLear** [comment]
lol for some reason it's not showing up for me :D https://etherpad.org/

**Comment by Gaxxey** [comment]
Make sure you empty cache and hard reload 🙂

**Comment by JohnMcLear** [comment]
[image](https://user-images.githubusercontent.com/220864/100381514-074d0f00-3011-11eb-83ba-35596713bc96.png)

**Comment by Gared** [comment]
@Gaxxey Thanks for your work and for fixing my ugly link 😄 
I will apply those changes also to our plugin page

**Comment by Gaxxey** [comment]
@JohnMcLear From your image, it seems some browsers are rendering the "etherpad" in the logo as text and adding a default font-family. I will need to convert that into an outline so it's rendered correctly

**Comment by JohnMcLear** [comment]
Latest chrome on windows

**Comment by slel** [comment]
> @JohnMcLear From your image, it seems some browsers are rendering the "etherpad" in the logo as text and adding a default font-family. I will need to convert that into an outline so it's rendered correctly

For reference: done at #37.

**Pull request merged**
