### PR TITLE
Adds React to the docs

### LINKED ISSUE #32: Mention Seballot in the footer
The redesing of https://etherpad.org done by @seballot is beautiful.

I suggest to mention him in the footer, he deserves it.

Sebastian: please, take credit!

### LINKED ISSUE #33: Should we use lazy loading for the images?
As they are large animated gifs.

https://web.dev/native-lazy-loading/

### PR DESCRIPTION
**Pull request by SamTV12345**
This pr introduces React to the documentation on GitHub pages. The main advantages are:
- better SEO (because I load the images lazy)
- better maintainability (component based)
- better version bumps (Just bump the version in the version.json and push your changes). We could automate that step in the release.js later.
- Add mention to the redesigner in the footer
- This should also fix the browser caching as React assigns a random hex code to the javascript file. So once the build is done everyone can be sure to have the correct version.

Closes #33
Closes #32

For it to work you need to go to Settings->Pages and change Source to "GitHub Actions"

### CODE REVIEW

**Comment by JohnMcLear** [comment]
cc @seballot 

I'm -1 such a large change that impacts so many files and inflates the repo "just" to address two very minor issues.

I'm also -1 because introducing react adds a technical knowledge barrier most people don't possess and potentially have made an active effort to avoid.

If @seballot is +1 tho I'm happy to squash and merge.

**Comment by SamTV12345** [comment]
Ok thanks for the feedback. I just had to move the dependencies around to the public directory as only the source and the public directory are put into the final dist directory. 

I would argue that most current developer know React better than pure HTML/JavaScript. React is pretty dominant and is used by the top 500 companies like Meta or Amazon.

**Comment by seballot** [comment]
Hi !

I agree with @JohnMcLear, this is a simple static website, there is no need of introducing a front end framework. Image lazyloading can be achieve with simple JS library. And not all devs are familiar with React. For example I'm not, I use Vue

Also I could not test your work, when I open index.html I have following error

image

Sorry @SamTV12345 I hope you didn't spend too much time on it? Did you discuss this change with somebody before starting working on it?

All the best,
Sebastian

**Comment by SamTV12345** [comment]
Hi. Thanks for the response. I can understand the decision. I'll keep the branch up if we want to create a more complex website with multiple routes, more content, reusable pages  etc. Did you do 

```bash
npm install 
npm run dev
```

Other than that you can render it to an actual webpage with `npm run build` and then open index.html in the `dist` folder.

**Comment by SamTV12345** [comment]
Other than that if you want to solve all or just 1 pull request feel free to create a pull request.

**Pull request merged**
